=== ABS0N/Webtechnology_2022_Fall/play.dtd
<!ELEMENT play (author,title,act+)>
<!ELEMENT act (title,scene+)>
<!ELEMENT scene (title,(speech | stagedir)+)>
<!ELEMENT speech (speaker, (line | stagedir)+)>
<!ELEMENT line (#PCDATA|stagedir)*>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT speaker (#PCDATA)>
<!ELEMENT stagedir (#PCDATA)>

=== ABS0N/Webtechnology_2022_Fall/hamlet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE play SYSTEM "play.dtd">
<!-- // Source: http://shakespeare.mit.edu/hamlet/ -->
<play>
    <author>William Shakespeare</author>
    <title>The Tragedy of Hamlet, Prince of Denmark</title>
    <act>
        <title>ACT I</title>
        <scene>
            <title>SCENE V.  Another part of the platform.</title>
            <speech>
                <speaker>HAMLET</speaker>
                <line>O all you host of heaven! O earth! What else?</line>
                <line>And shall I couple hell? O, fie! Hold, hold, my heart;</line>
                <line>And you, my sinews, grow not instant old,</line>
                <line>But bear me stiffly up. Remember thee!</line>
                <line>Ay, thou poor ghost, while memory holds a seat</line>
                <line>In this distracted globe. Remember thee!</line>
                <line>Yea, from the table of my memory</line>
                <line>I'll wipe away all trivial fond records,</line>
                <line>All saws of books, all forms, all pressures past,</line>
                <line>That youth and observation copied there;</line>
                <line>And thy commandment all alone shall live</line>
                <line>Within the book and volume of my brain,</line>
                <line>Unmix'd with baser matter: yes, by heaven!</line>
                <line>O most pernicious woman!</line>
                <line>O villain, villain, smiling, damned villain!</line>
                <line>My tables,--meet it is I set it down,</line>
                <line>That one may smile, and smile, and be a villain;</line>
                <line>At least I'm sure it may be so in Denmark:</line>
                <stagedir>Writing</stagedir>
                <line>So, uncle, there you are. Now to my word;</line>
                <line>It is 'Adieu, adieu! remember me.'</line>
                <line>I have sworn 't.</line>
            </speech>
            <stagedir>Enter HORATIO and MARCELLUS</stagedir>
            <speech>
                <speaker>HORATIO</speaker>
                <line>
                    <stagedir>Within</stagedir>
                    My lord, my lord,--
                </line>
            </speech>
            <speech>
                <speaker>MARCELLUS</speaker>
                <line>
                    <stagedir>Within</stagedir>
                    Lord Hamlet,--
                </line>
            </speech>
            <speech>
                <speaker>HORATIO</speaker>
                <line>
                    <stagedir>Within</stagedir>
                    Heaven secure him!
                </line>
            </speech>
            <speech>
                <speaker>HAMLET</speaker>
                <line>So be it!</line>
            </speech>
            <speech>
                <speaker>HORATIO</speaker>
                <line>
                    <stagedir>Within</stagedir>
                    Hillo, ho, ho, my lord!
                </line>
            </speech>
            <speech>
                <speaker>HAMLET</speaker>
                <line>Hillo, ho, ho, boy! come, bird, come.</line>
            </speech>
        </scene>
    </act>
</play>
